name: Release

on:
  pull_request_target:
    types:
      - closed
    branches: [main]

jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Installing dependencies
        run: npm ci
      - name: Validating build
        run: npm run validate
      - name: Configure Git
        run: |
          git config user.name 'sh4hids'
          git config user.email 'sh4hids@users.noreply.github.com'
      - name: Publish package on NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
